### ISSUE TITLE
I think you mean ADD not ADHD

### ISSUE THREAD

**Issue by ccfman2004** [x74353/SaveAmphetamine#11]
I think you mean to say ADD instead of ADHD as the H in there means Hyper-Activity where the person can't sleep and those meds would make the condition worse.  People with ADHD are advised not to take anything such as caffeine or energy drinks.

**Comment by x74353** [comment]
Hey there. Thanks for your comment. I'm not too hung up on this, and certainly you may be correct. My usage of the "ADHD" term comes from sources such as [this](https://www.additudemag.com/slideshows/add-vs-adhd/) where the following is stated:

> ADHD is the official, medical term for the condition — regardless of whether a patient demonstrates symptoms of hyperactivity. ADD is a now-outdated term that is typically used to describe inattentive-type ADHD, which has symptoms including disorganization, lack of focus, and forgetfulness. People with inattentive ADHD are not hyper or impulsive.
