### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by saagarjha** [x74353/SaveAmphetamine#4]
(I posted this [on Hacker News](https://news.ycombinator.com/item?id=25608084) too, but figured you might not see it so I’m putting a copy here.)

I do app review policy for iSH, which went though [a similar situation recently](https://ish.app/blog/app-store-removal) where we managed to convince Apple that they had misinterpreted their review guidelines. If you’re looking for help to get Amphetamine approved as it should, feel free to contact me at saagar@saagarjha.com. I’d be really disappointed to see Amphetamine lose its years of brand value over such a petty review decision.

**Comment by x74353** [comment]
@saagarjha Thank you so much for the offer of help. Please excuse my late reply to your super awesome and insightful email. I am hoping to get a response out to you later on today.
