### ISSUE TITLE
A blessing in disguise!

### ISSUE THREAD

**Issue by dm17** [x74353/SaveAmphetamine#5]
Let me explain why this is a blessing in disguise:
"Amphetamine" is literally true. Amphetamine keeps a computer as well as a human up all night! The description of this is a literal truth, and nothing in the program or using it opens up the interpretation that using Amphetamine to keep a computer up all night is bad for a human. I'm guessing the relative effects of keeping a computer up all night is under the discretion of its user. It is false and arguable in the court of law that an amphetamine software that keeps a computer up all night cannot be used the same way as an amphetamine that keeps a human up all night. Software and drugs are not the same thing. 

Perhaps a counter lawsuit should be filed against Apple for implying it is selling fruit!

Thank you for standing up and not changing the name! This is a very destructive culture war that has been waged on us by forces unknown to those who wage it.

**Comment by x74353** [comment]
Thanks for your support! Glad it all worked out! I had a pretty awesome backup plan though. Oh well. :)
