### ISSUE TITLE
Why stick with AppStore?

### ISSUE THREAD

**Issue by sirnacnud** [x74353/SaveAmphetamine#9]
Are there valid business reasons to not release Amphetamine outside the AppStore?

**Comment by geenva** [comment]
He'll need to spend extra money to sign the app, and if he does not, it might potentially turn down users. It will also be hard to track download numbers unless with a tracker. By releasing on the App Store, he will bypass the "Allow apps from unidentified developers" prompt.

**Comment by x74353** [comment]
Hi @sirnacnud, @geenva is spot-on with the reasons why. App development is a part-time gig/hobby for me. The App Store simplifies a lot of the cost, distribution, and marketing issues that I would otherwise have to handle on my own.
